[package]
name = "imap-flow"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bounded-static = "0.5.0"
bytes = "1.5.0"
imap-codec = { version = "1.0.0", features = ["quirk_crlf_relaxed", "bounded-static"] }
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["io-util"] }

[dev-dependencies]
argh = "0.1.12"
tokio = { version = "1.32.0", features = ["macros", "net", "rt"] }
tokio-rustls = "0.24.1"
webpki-roots = "0.25.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dev-dependencies.rsasl]
version = "2.0.0"
default-features = false
features = [
    # This is not a default feature.
    "provider",
    # <default>
    "config_builder",
    "registry_static",
    "scram-sha-1",
    "scram-sha-2",
    "anonymous",
    "external",
    "oauthbearer",
    "xoauth2",
    "plain",
    "login",
    # We want the default features w/o "gssapi" to simplify the build.
    # GSSAPI requires additional libraries, such as `libkrb5-dev` (on Ubuntu).
    # "gssapi",
    # </default>
]

[workspace]
resolver = "2"
members = [
    "proxy",
    "tag-generator",
    "tasks",
]

[patch.crates-io]
imap-types = { git = "https://github.com/duesee/imap-codec", branch = "v2" }
imap-codec = { git = "https://github.com/duesee/imap-codec", branch = "v2" }
