[package]
name = "imap-flow"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
expose_stream = []

[dependencies]
bounded-static = "0.5.0"
bytes = "1.5.0"
imap-codec = { version = "2.0.0", features = ["quirk_crlf_relaxed", "bounded-static", "ext_id", "ext_sort_thread", "ext_binary", "ext_uidplus"] }
imap-types = { version = "2.0.0", features = ["ext_id", "ext_sort_thread", "ext_binary", "ext_uidplus"] }
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["io-util", "sync", "time"] }
tracing = "0.1.40"

[dev-dependencies]
rand = "0.8.5"
tag-generator = { path = "tag-generator" }
tokio = { version = "1.32.0", features = ["full"] }

[workspace]
resolver = "2"
members = [
    "flow-test",
    "proxy",
    "tag-generator",
    "tasks",
]

[patch.crates-io]
imap-codec = { git = "https://github.com/duesee/imap-codec" }
imap-types = { git = "https://github.com/duesee/imap-codec" }
