[package]
name = "imap-flow"
description = "Thin abstraction over IMAP's distinct protocol flows"
keywords = ["email", "imap", "protocol", "network"]
categories = ["email", "network-programming"]
version = "0.1.0"
repository = "https://github.com/duesee/imap-flow" # TODO
edition = "2021"
license = "MIT OR Apache-2.0"
exclude = [
    ".github",
]

[features]
default = ["stream"]
expose_stream = []
stream = ["dep:rustls", "dep:tokio", "dep:tokio-rustls"]

[dependencies]
bounded-static = "0.5.0"
bytes = "1.5.0"
imap-codec = { version = "2.0.0", features = ["starttls", "quirk_crlf_relaxed", "bounded-static", "ext_condstore_qresync", "ext_login_referrals", "ext_mailbox_referrals", "ext_id", "ext_sort_thread", "ext_binary", "ext_metadata", "ext_uidplus"] }
imap-types = { version = "2.0.0", features = ["starttls", "ext_condstore_qresync", "ext_login_referrals", "ext_mailbox_referrals", "ext_id", "ext_sort_thread", "ext_binary", "ext_metadata", "ext_uidplus"] }
rustls = { version = "0.23.1", optional = true }
thiserror = "1.0.49"
tokio = { version = "1.32.0", optional = true, features = ["io-util", "macros", "net"] }
tokio-rustls = { version = "0.26.0", optional = true }
tracing = "0.1.40"

[dev-dependencies]
rand = "0.8.5"
tag-generator = { path = "tag-generator" }
tokio = { version = "1.37.0", features = ["full"] }

[workspace]
resolver = "2"
members = [
    "flow-test",
    "proxy",
    "tag-generator",
    "tasks",
]

[patch.crates-io]
imap-codec = { git = "https://github.com/duesee/imap-codec" }
imap-types = { git = "https://github.com/duesee/imap-codec" }
