[package]
name = "imap-flow"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bounded-static = "0.5.0"
bytes = "1.5.0"
imap-codec = { version = "1.0.0", features = ["quirk_crlf_relaxed", "bounded-static"] }
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["io-util"] }
