[package]
name = "integration-test"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bstr = { version = "1.9.1", default-features = false }
bytes = "1.6.0"
imap-codec = "2.0.0"
imap-next = { path = ".." }
imap-types = "2.0.0"
tokio = { version = "1.37.0", features = ["macros", "net", "rt", "time"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# Fix minimal versions
lazy_static = "1.4.0"
