[package]
name = "tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
imap-codec = "1.0.0"
imap-flow = { path = ".." }
tag-generator = { path = "../tag-generator" }
thiserror = "1.0.50"
tokio = { version = "1.32.0", features = ["full"] }
