[[services]]
name = "TLS/Insecure"

[services.bind]
encryption = "Tls"
host = "127.0.0.1"
port = 1993

[services.bind.identity]
type = "CertificateChainAndLeafKey"
certificate_chain_path = "localhost.pem"
leaf_key_path = "localhost-key.pem"

[services.connect]
encryption = "Insecure"
host = "127.0.0.1"
port = 143
