on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@f5473ace9aeee8b97717b281e26980aa5097023f
        with:
          project-url: https://github.com/users/duesee/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
